### ISSUE TITLE
Compile/Build Problem

### ISSUE THREAD

**Issue by KRRAlremeithi** [ForgeFN/Forge#11]
When I compile/build forge.dll it gives errors and warnings 
and how do you host?
![image](https://user-images.githubusercontent.com/125153811/218276990-35cc2680-194d-4a2d-84be-7b805deb20ee.png)

(and some ppl want a tutorial so yeah)

**Comment by UWUFN** [comment]
you are a skid + ratio + L bozo

**Comment by KRRAlremeithi** [comment]
> 

this isnt a fix i need fix

**Comment by KRRAlremeithi** [comment]
> you are a skid + ratio + L bozo

btw who still says that bro using Instagram Reels ;(

**Comment by Noggo123** [comment]
💀

**Comment by Milxnor** [comment]
release

**Comment by KRRAlremeithi** [comment]
> release

how do i host with dll
