### ISSUE TITLE
Creative tool

### ISSUE THREAD

**Issue by BallsFN** [ForgeFN/Forge#15]
if (Globals::bisCreativeToolsEnabled) {
           Mini = UObject::FindObjectFast<UFortWeaponItemDefinition>("/Game/Athena/Items/Consumables/ShieldSmall/Athena_ShieldSmall.Athena_ShieldSmall");
           Count = 1;

///

if (Globals::bisCreativeToolsEnabled == true) {
			GiveAbility(Pawn->AbilitySystemComponent, Delete->CreateDefaultObject());
			GiveAbility(Pawn->AbilitySystemComponent, Rotate->CreateDefaultObject());
			GiveAbility(Pawn->AbilitySystemComponent, RetaçaoReverse->CreateDefaultObject());
			GiveAbility(Pawn->AbilitySystemComponent, Place->CreateDefaultObject());
			GiveAbility(Pawn->AbilitySystemComponent, Animation->CreateDefaultObject());
			GiveAbility(Pawn->AbilitySystemComponent, MoveTool->CreateDefaultObject());
			GiveAbility(Pawn->AbilitySystemComponent, Espelhar->CreateDefaultObject());
			GiveAbility(Pawn->AbilitySystemComponent, ClickFail->CreateDefaultObject());
			GiveAbility(Pawn->AbilitySystemComponent, ExitClick->CreateDefaultObject());

**Comment by Milxnor** [comment]
bro what
